main:
	gcc -g main.c prompt.c
	gcc -g main.c shellw.c
	gcc -g main.c warp.c
	gcc -g main.c peek.c
	gcc -g main.c pastevent.c
	gcc -g main.c seek.c
	gcc -g main.c proclore.c
	gcc -g main.c iman.c
	gcc -g main.c signalsfile.c
	gcc -g main.c bg.c
	gcc -g main.c fgandbg.c
	gcc -g main.c neonate.c
	gcc -g main.c activities.c
	gcc -g main.c extrapiping.c
	gcc -g main.c redirect.c
	gcc -g main.c signalsfile.c
